In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier,VotingClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [4]:
from xgboost import XGBClassifier

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
df = pd.read_csv("Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [8]:
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])

In [9]:
df['Species'].unique()

array([0, 1, 2])

In [10]:
X = df.drop('Species',axis=1)
y = df['Species']

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [13]:
ada_model = AdaBoostClassifier(n_estimators=100,random_state=42)
ada_model.fit(X_train,y_train)
y_pred_ada = ada_model.predict(X_test)

D:\Python\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [14]:
gb_model = GradientBoostingClassifier(n_estimators=100,random_state=42)
gb_model.fit(X_train,y_train)

y_pred_gb = gb_model.predict(X_test)

In [15]:
xgb_model = XGBClassifier(n_estimators=100,use_label_encoder=False,eval_metric='mlogloss',random_state=42)
xgb_model.fit(X_train,y_train)

y_pred_xgb = xgb_model.predict(X_test)

D:\Python\lib\site-packages\xgboost\core.py:158: UserWarning: [23:12:42] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0ed59c031377d09b8-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


In [18]:
ada_accuracy = accuracy_score(y_test,y_pred_ada)
ada_report = classification_report(y_test,y_pred_ada)
ada_cm = confusion_matrix(y_test,y_pred_ada)

print(f"AdaBoost Accuracy:{ada_accuracy:.2f}")
print("AdaBoost Classification Report:\n",ada_report)
print("AdaBoost Confusion Matrix:\n",ada_cm)

AdaBoost Accuracy:1.00
AdaBoost Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

AdaBoost Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [19]:
gb_accuracy = accuracy_score(y_test,y_pred_gb)
gb_report = classification_report(y_test,y_pred_gb)
gb_cm = confusion_matrix(y_test,y_pred_gb)

print(f"Gradient Accuracy:{ada_accuracy:.2f}")
print("Gradient Classification Report:\n",gb_report)
print("Gradient Confusion Matrix:\n",gb_cm)

Gradient Accuracy:1.00
Gradient Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Gradient Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [20]:
xgb_accuracy = accuracy_score(y_test,y_pred_xgb)
xgb_report = classification_report(y_test,y_pred_xgb)
xgb_cm = confusion_matrix(y_test,y_pred_xgb)

print(f"XGBoost Accuracy:{ada_accuracy:.2f}")
print("XGBoost Classification Report:\n",xgb_report)
print("XGBoost Confusion Matrix:\n",xgb_cm)

XGBoost Accuracy:1.00
XGBoost Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

XGBoost Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [21]:
print(f"AdaBoost Accuracy : {ada_accuracy:.2f}")
print(f"Gradient Boosting Accuracy: {gb_accuracy:.2f}")
print(f"XGBoost Accuracy: {xgb_accuracy:.2f}")

AdaBoost Accuracy : 1.00
Gradient Boosting Accuracy: 1.00
XGBoost Accuracy: 1.00
